# Generated by Django 4.2.1 on 2023-05-13 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_test_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
