# Generated by Django 4.2.1 on 2023-05-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0008_product_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categorie',
            field=models.CharField(choices=[('shoes', 'Shoes'), ('tops', 'Tops'), ('hats', 'Hats')], max_length=20),
        ),
    ]
