# Generated by Django 4.2.1 on 2023-06-21 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0013_order_address_order_first_name_order_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='last_name',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='number',
            new_name='phoneNumber',
        ),
    ]
