# Generated by Django 4.2.1 on 2023-06-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0014_rename_first_name_order_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_state',
            field=models.CharField(choices=[('OTW', 'Otw'), ('DELIVERED', 'Delivered'), ('PROBLEM', 'Problem'), ('PENDING', 'Pending')], default='PENDING', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='order_state',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('CANCELED', 'Canceled')], default='UNPAID', max_length=50),
        ),
    ]
