# Generated by Django 4.2.1 on 2023-06-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0015_order_delivery_state_order_order_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_state',
            field=models.CharField(choices=[('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELED', 'Canceled'), ('PENDING', 'Pending')], default='PENDING', max_length=50),
        ),
    ]
