# Generated by Django 4.2.1 on 2023-07-14 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0020_notification_notification_notification_read_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='eCommerce.order'),
        ),
    ]
