# Generated by Django 4.2.1 on 2023-07-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0021_notification_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('ON DELIVERY', 'On Delivery'), ('ONLINE', 'Online')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_state',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('CANCELED', 'Canceled')], default='UNPAID', max_length=50),
        ),
    ]
