# Generated by Django 4.2.1 on 2023-08-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0024_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantities',
            field=models.IntegerField(default=1),
        ),
    ]
