# Generated by Django 4.2.1 on 2023-08-19 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0028_cartorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='buyer',
        ),
    ]
