# Generated by Django 4.2.1 on 2023-08-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0029_remove_cartorder_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(to='eCommerce.product'),
        ),
    ]
