# Generated by Django 4.2.1 on 2023-08-20 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0031_cartquantities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartquantities',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartquantities',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartOrder',
        ),
        migrations.DeleteModel(
            name='CartQuantities',
        ),
    ]
